### ISSUE TITLE
[US02] Cadastro de Alunas

### ISSUE THREAD

**Issue by Jvsoutomaior** [fga-eps-mds/2022.2-Amis-Doc#103]
## História do usuário

Eu como Administradora/Assistente desejo cadastrar os dados das alunas na plataforma para que eu possa registrar o controle dos dados das alunas

## Protótipo 

[Tela de cadastro de alunas](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1677%253A1752%26scaling%3Dscale-down-width%26page-id%3D1677%253A170%26starting-point-node-id%3D1677%253A511)

## Critérios de aceitação

- [x] Campos fazendo as devidas validações
- [x] Realizar o cadastro de aluna
- [x] Realizar a atualização de aluna
- [x] Realizar a exclusão de aluna
- [x] Feedback da aplicação ao realizar o cadastro/alteração/exclusão
- [x] Validar a usabilidade

## Tarefas:

- [x] #53 
- [x] #52

**Comment by marioandunb** [comment]
Cadastro de alunas entregue conforme expectativas.

**Comment by CaioSulz** [comment]
![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/799afe28-5c9e-43c3-967c-f7b4347be4f0)

**Comment by CaioSulz** [comment]
Formulário validação Alunas

![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/c8dca662-6a58-4f9f-bce9-86ce0089fe2c)

![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/49a0e88f-3136-4b1e-a36f-053f114e13f4)
