### ISSUE TITLE
Dojo de Front-end

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#17]
**Descrição:**

Ensinar conceitos básicos e mostrar alguns comandos e funcionalidades do React.

**Tasks**
- [x] Marcar o Dojo
- [x] Preparar o ambiente e o material
- [x] Realizar o Dojo 

**Critérios de aceitação:**
- [x] Gravar o Dojo

**Comment by andrelucasf** [comment]
Dojo realizado no dia 17/11/2022. 

Participantes: André Lucas, Caio, Eduardo, Fabrício, Italo, João Victor e Paulo.
