### ISSUE TITLE
Dojo de Back-end

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#18]
**Descrição:**

Ensinar a teoria do backend e funcionalidades básicas do framework.

**Tasks**
- [x] Marcar o Dojo
- [x] Realizar o Dojo

**Critérios de aceitação:**
- [x] Gravar o Dojo

**Comment by thiagolsg** [comment]
[Repositório do Dojo](https://github.com/thiagolsg/CRUD_FastAPI.git)

**Comment by thiagolsg** [comment]
Dojo realizado e aula esta gravada e disponível na equipe do teams
