### ISSUE TITLE
Estudar Tecnologias de Backend

### ISSUE THREAD

**Issue by gabrielapivetta** [fga-eps-mds/2022.2-Amis-Doc#19]
**Descrição:**

Estudar as tecnologias de backend para escolher a mais apropriada para o projeto.

**Tasks**
- [x] Estudar os frameworks e bibliotecas de python para backend

**Critérios de aceitação:**
- [x] Relatar nos comentários o framework escolhido

**Comment by thiagolsg** [comment]
# FastAPI
Oque é [aqui](https://www.treinaweb.com.br/blog/o-que-e-fastapi)
Como fazer um CRUD [aqui](https://www.treinaweb.com.br/blog/criando-o-primeiro-crud-com-fastapi)
Como criar testes [aqui](https://fastapi.tiangolo.com/tutorial/testing/) ,  video tutorial [aqui](https://www.youtube.com/watch?v=uk7EcDIZEfY)

# Flask
Oque é [aqui](https://www.treinaweb.com.br/blog/o-que-e-flask)
Como fazer um CRUD [aqui](https://itnext.io/build-a-simple-crud-todo-app-with-python-flask-in-100-lines-of-code-or-less-97d8792f24be)
Como criar testes [aqui](https://medium.com/@otaviobn/tdd-com-flask-e-unittest-3f66036a240b)

# Django
Oque é [aqui](https://kenzie.com.br/blog/django/)
Como fazer um CRUD [aqui](https://www.geeksforgeeks.org/django-rest-api-crud-with-drf/)
Como testar [aqui](https://medium.com/developer-student-clubs-tiet/test-and-improve-your-rest-apis-with-pytest-3f873dbb6866)

# FastAPI vs DjangoREST

[resumo sobre os dois e suas diferenças](https://medium.com/@ShortHills_Tech/django-vs-fast-api-a-detailed-comparison-df8d00f3c3b2)

**Comment by jps12** [comment]
Após os estudos e alguns debates entre a equipe, foi decido que o fremework a ser utilizado no backend da aplicação será o [FastAPI](https://fastapi.tiangolo.com/). Dentre os principais motivos para a escolha são:
- Baixa curva de aprendizagem
- Simplicidade 
- Velocidade nas operações
- Comunidade ativa
