### ISSUE TITLE
Documentar a sprint 1

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#27]
**Descrição:**

Documentar o que foi planejado e o resultado da sprint 1

**Tasks**
- [x] Documentar o planejamento
- [x] Documentar o resultado da sprint

**Critérios de aceitação:**
- [x] Todo o planejamento e resultado da sprint estar documentado

**Comment by jps12** [comment]
@fxred Linkar o PR com a issue pelo zenhub

**Comment by fxred** [comment]
@jps12 feito
