### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#39]
**Descrição:**

Documentar o que foi planejado e o resultado da sprint 2

**Tasks**
- [ ] Documentar o planejamento
- [ ] Documentar o resultado da sprint

**Critérios de aceitação:**
- [ ] Todo o planejamento e resultado da sprint estar documentado

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/39?planning-poker) with Zenhub @thiagolsg @andrelucasf @gabrielapivetta @KalebeLopes @fxred @ItaloBrunoM @paulohborba @FabricioDeQueiroz @CaioSulz @Jvsoutomaior
