### ISSUE TITLE
Tela Cadastro de Alunas

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#52]
## Descrição:

Criação da tela de cadastro de alunas

## História de Usuário:

#103

## Tarefas:

* Tela fiel ao protótipo
* Integração com o service
* Cadastrar, editar, visualizar e excluir Alunas.
* Validação nos inputs
* Mensagem de retorno ao realizar cadastro
* Validar com o cliente

## Critérios de aceitação:

- [x] Implementar tela de Alunas
- [x] Criar testes
- [x] Formulário de aceitação com o cliente

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/52?planning-poker) with Zenhub @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @jps12 @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg

**Comment by andrelucasf** [comment]
Necessária criação dos testes e completar as ações de editar e excluir.

**Comment by KalebeLopes** [comment]
foi adicionado os critérios de aceitação do usuário
