### ISSUE TITLE
Endpoints Cadastro de Alunas

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#53]
## Descrição:

Criação do endpoint de cadastro de alunas

## História de Usuário:

#103

## Critérios de aceitação

* Passar em todos os Testes
* Pylint acima de seis pontos 
* Conexão com o banco de dados em produção

## Tarefas:

- [x] Criar Testes
- [x] Configurar ambiente
- [x] Implementar CRUD
- [x] Conexão com o banco em produção
- [x] Refatoração do código

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/53?planning-poker) with Zenhub @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @jps12 @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg

**Comment by jps12** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/53?planning-poker) with Zenhub @andrelucasf
