### ISSUE TITLE
Criação da Tela Inicial

### ISSUE THREAD

**Issue by thiagolsg** [fga-eps-mds/2022.2-Amis-Doc#54]
## Descrição:

Criação das tela inicial da aplicação, conforme o protótipo

## História de Usuário:

#69

## Tarefas:

- [x] Implementar tela conforme o protótipo validado
- [x] Integrar com azure

## Critérios de aceitação:

- [x] Estar de acordo com o protótipo

**Comment by andrelucasf** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/54?planning-poker) with Zenhub @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @jps12 @Jvsoutomaior @KalebeLopes @paulohborba @thiagolsg
