### ISSUE TITLE
[US03] Cadastro de Turmas

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#61]
## História do usuário

Eu como Administrador desejo cadastrar turmas na plataforma para que eu possa controlar a quantidade de alunas por turma para prestação de contas.

## Protótipo 
[Tela de cadastro de turmas](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1677%253A2123%26scaling%3Dscale-down-width%26page-id%3D1677%253A170%26starting-point-node-id%3D1677%253A511)

## Critérios de aceitação:

A página deve:
- [ ] Realizar corretamente cadastro, atualização e exclusão de turmas
- [ ] Prover devido feedback ao realizar cadastro, alteração, exclusão e interagir com o site em geral
- [ ] Ao clicar no botão cadastrar no topo direito da página, deve aparecer uma página menor com os seguintes campos para serem preenchidos:
    - Nome da turma
	- Descrição
	- Capacidade da turma
	- Nº de vagas disponíveis
	- Data de início
	- Data de fim
	- Horário de início
	- Horário de fim
- [ ] A ação de cadastrar está funcionando
- [ ] Os campos de visualização exibem os seguintes dados
    - Nome da turma
    - Capacidade da turma
	- Nº de vagas disponíveis
    - Data de início
	- Data de fim
	- Horário de início
	- Horário de fim
- [ ] Ao clicar no botão de editar, deve aparecer uma página menor com os campos para serem editados:
    - Nome da turma
    - Capacidade da turma
	- Data de fim
	- Horário de início
	- Horário de fim
- [ ] Ao clicar no botão de excluir, ao lado da turma cadastrada, aparece a seguinte mensagem "Você tem certeza de que deseja excluir?" com as opções "sim" e "não"
- [ ] Ao aceitar a exclusão, a turma é excluída

## Tarefas:

- [x] #102
- [x] #101

**Comment by marioandunb** [comment]
Acredito que o protótipo não esteja alinhado com as expectativas de informações a serem tratadas no cadastro das turmas. Informações como número de vagas, vagas preenchidas, horários, etc, deveriam, a meu ver, fazer parte do conteúdo deste cadastro.

**Comment by marioandunb** [comment]
Validado!

**Comment by marioandunb** [comment]
Cadastro de turmas entregue conforme expectativas.

**Comment by CaioSulz** [comment]
Formulário validação Turmas

![image](https://user-images.githubusercontent.com/98036264/215925267-b90e0bbb-439c-47fc-abf0-2ea7b416c47f.png)
![image](https://user-images.githubusercontent.com/98036264/215925311-a76bd27a-05aa-4789-ac80-2c5212c4424a.png)
![image](https://user-images.githubusercontent.com/98036264/215925335-4990b87a-9ce4-4cb7-abe5-a129bd2e0398.png)
