### ISSUE TITLE
[US05] Cadastro de receitas

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#63]
## História do usuário

Eu como Administrador desejo cadastrar receitas na plataforma para que eu possa disponibilizar as receitas para os usuário.

### Tela geral de receitas
[Tela geral](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1785%253A2242%26t%3DfhQF4p4sazUPnIwi-1).

### Campo para cadastro de receitas
[Formulário de cadastro](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1785%253A2016%26t%3DfhQF4p4sazUPnIwi-1).

### Tela de visualização de receita
[Visualização de receita](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1785%253A1954%26t%3DfhQF4p4sazUPnIwi-1).

## Critérios de aceitação

- [ ]  Realização correta do cadastro, atualização e exclusão de receitas
- [ ]  Ao clicar em "Cadastrar Receita" deve abrir uma janela com os campos:
    * Nome da receita
    * Ingredientes
    * Modo de preparo
- [ ] Os campos "Ingredientes" e "Modo de preparo" devem conter um botão de adição e remoção
- [ ] Ao clicar no botão de adição, um Ingrediente/Modo de preparo é adicionado
- [ ] Ao clicar no botão de remoção, um Ingrediente/Modo de preparo é adicionado
- [ ] Ao clicar no botão "Cadastrar" na janela, a receita deverá aparecer na tela de receitas
- [ ] Ao clicar no botão de excluir receita, aparecer uma janela de confirmação de exclusão
- [ ] Botão de "Editar Receita" abre uma janela com os campos a serem editados

## Tarefas:
- [ ]  https://github.com/fga-eps-mds/2022.2-Amis-Doc/issues/115
- [x] #116

**Comment by marioandunb** [comment]
Validado!

**Comment by CaioSulz** [comment]
Formulário de validação Receitas
![image](https://user-images.githubusercontent.com/98036264/216772833-ba179acd-2339-493e-88a0-6b1f59c3ec1d.png)
![image](https://user-images.githubusercontent.com/98036264/216772858-b1511177-d339-4b83-a745-63c7394d99f1.png)
![image](https://user-images.githubusercontent.com/98036264/216772878-4f98f44a-3f54-4864-b8b4-c6a102718c34.png)
![image](https://user-images.githubusercontent.com/98036264/216772888-ccaad7aa-c315-4461-816f-fd504e8e0560.png)
