### ISSUE TITLE
[US06] Login

### ISSUE THREAD

**Issue by CaioSulz** [fga-eps-mds/2022.2-Amis-Doc#66]
## História do usuário

Eu como Administrador/Assistente desejo fazer login na plataforma para que eu possa acessar os serviços e funcionalidades.

## Protótipo

[Tela de login](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D450%253A201%26t%3DX7N6brBnQgyFjL7C-1)

## Critérios de aceitação

Ao clicar no botão entrar, a aplicação deve verificar:
- [x] Se o email digitado é válido
- [x] Se o email está cadastrado
- [x] Se a senha condiz com o email cadastrado (se estiver)
- [x] Se as credenciais estiverem de acordo com o cadastro, o usuário deve ser redirecionado para a área logada
- [x] Se as credenciais não estiverem de acordo, um pop-up deve ser exibido com o nome do(s) campo(s) invalidado(s)

**Comment by marioandunb** [comment]
Validado!

**Comment by CaioSulz** [comment]
Formulário de validação Login e Logout

![image](https://user-images.githubusercontent.com/98036264/216772755-65038989-052f-4952-800b-56d9b798dc42.png)
![image](https://user-images.githubusercontent.com/98036264/216772768-04bf10d8-5d23-43f0-bd51-7b6f34fc16f7.png)
