### ISSUE TITLE
[US10] Visualização das receitas 

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#67]
## História do usuário

Eu como Usuário Comum desejo visualizar as receitas cadastradas para que eu possa orientar na preparação do alimento/refeição

### Tela geral de receitas para usuário comum
[Tela geral sem acesso ao botão cadastrar](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1792%253A516%26t%3DN0Je076amrJoLZRt-1).

### Tela de visualização de receita
[Tela de receita sem botões de edição e exclusão de receita](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1792%253A454%26t%3DN0Je076amrJoLZRt-1).

## Critérios de aceitação

- [x] Visualização de todas as receitas na tela geral de receitas
- [x] Clicar na receita e abrir tela de detalhes da receita
- [x] Na aba de detalhes mostrar ingredientes e modo de preparo

## Tarefas:

- [x] #116

**Comment by marioandunb** [comment]
Validado!

**Comment by CaioSulz** [comment]
Formulário de validação Receitas
![image](https://user-images.githubusercontent.com/98036264/216772833-ba179acd-2339-493e-88a0-6b1f59c3ec1d.png)
![image](https://user-images.githubusercontent.com/98036264/216772858-b1511177-d339-4b83-a745-63c7394d99f1.png)
![image](https://user-images.githubusercontent.com/98036264/216772878-4f98f44a-3f54-4864-b8b4-c6a102718c34.png)
![image](https://user-images.githubusercontent.com/98036264/216772888-ccaad7aa-c315-4461-816f-fd504e8e0560.png)
