### ISSUE TITLE
[US11] Visualização de dados de pessoas impactadas no projeto

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#69]
## História do usuário

Eu como Usuário Comum desejo visualizar dados das pessoas impactadas pelo projeto para que  possa dar transparência e visibilidade para as ações da ONG

## Protótipo
[Tela de exibição de dados de pessoas impactadas no projetos](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1211%253A104%26t%3DX7N6brBnQgyFjL7C-1)

## Critérios de aceitação

- [x] Exibição correta do número de pessoas atendidas
- [x] Exibição correta do número de formações profissionais
- [x] Atualização dos números em tempo real

## Tarefas:

- [x] #107
- [x] #109

**Comment by marioandunb** [comment]
Validado!
