### ISSUE TITLE
[US01] Cadastro de assistentes

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#84]
## História do usuário

Eu como administrador desejo cadastrar assistentes sociais para que eu possa controlar o acesso às funcionalidades do sistema

## Protótipo

[Tela de cadastro de assistentes](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fproto%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1677%253A2569%26scaling%3Dscale-down-width%26page-id%3D1677%253A170%26starting-point-node-id%3D1677%253A511)

## Critérios de aceitação

A página deve:
- [x] Realizar corretamente cadastro, atualização e exclusão de usuários assistentes
- [x] Prover devido feedback ao realizar cadastro, alteração, exclusão e interagir com o site em geral
- [x] Ao clicar no botão cadastrar no topo direito da pagina, deve aparecer uma pagina menor com os seguintes campos para serem preenchidos:
    - Nome
    - CPF
    - Login
    - Senha
    - Observações
    - Administrador (sim ou não)
- [x] A ação de cadastrar está funcionando
- [x] Os campos de visualização exibem os seguintes dados
    - Nome
    - CPF
    - Observações
    - Administrador (sim ou não)
- [x] Ao clicar no botão de editar, deve aparecer uma página menor com os campos para serem editados:
   - Nome
   - CPF
   - Administrador (sim ou não)
- [x] Ao clicar no botão de excluir, ao lado da assistente cadastrada, aparece a seguinte mensagem "Você tem certeza de que deseja excluir?" com as opções "Sim" e "Não"
- [x] Ao aceitar a exclusão, a assistente é excluída e não aparece mais na tela

**Comment by marioandunb** [comment]
Bom dia! No protótipo está escrito "Tela de cadastro de alunas". Acho que seria interessante haver a inclusão de um campo para "observações", que pode vir a ser utilizado caso haja alguma eventualidade, como reduzida disponibilidade de horas, etc.

**Comment by paulohborba** [comment]
> Bom dia! No protótipo está escrito "Tela de cadastro de alunas". Acho que seria interessante haver a inclusão de um campo para "observações", que pode vir a ser utilizado caso haja alguma eventualidade, como reduzida disponibilidade de horas, etc.

Boa noite professor, as mudanças foram feitas.

**Comment by marioandunb** [comment]
Não consegui ver claramente o protótipo. O campo "observações" foi criado?

**Comment by marioandunb** [comment]
Cadastro entregue conforme expectativas.

**Comment by CaioSulz** [comment]
Formulário validação Assistentes

![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/5ab91afc-8792-4e03-aa2c-c92072a54bac)
![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/9eaf2636-cd34-4cfd-b52a-0f43dac37e2d)
