### ISSUE TITLE
[US04] Alocar alunas nas turmas

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#85]
## História do usuário

Eu como Administrador/Assistente desejo cadastrar alunas nas turmas na plataforma para que eu possa controlar a quantidade de alunas por turmas para prestação de contas

## Protótipo

[Cadastro de alunas nas turmas](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D1355%253A609%26t%3DN0Je076amrJoLZRt-1)

## Critérios de aceitação
- [ ] Realizar corretamente cadastro, atualização e exclusão de de alunas nas turmas
- [ ] A turma está salvando corretamente as alunas cadastradas
- [ ] Visualização correta da turma cadastrada
- [ ] Não poder cadastrar uma aluna em mais de uma turma
- [ ] Não poder cadastrar uma aluna em turma com vagas cheias
- [ ] Não poder editar uma aluna de uma turma já finalizada
- [ ] Não poder excluir uma aluna de uma turma já finalizada
- [ ] Prover devido feedback ao realizar cadastro, alteração e exclusão
- [ ] Responder corretamente para todas as opções escolhidas na tela

## Tarefas:

- [x] #105

**Comment by marioandunb** [comment]
Validado!

**Comment by marioandunb** [comment]
Processo de matrícula das alunas nas turmas aprovado de acordo com as expectativas e requisitos.

**Comment by CaioSulz** [comment]
Formulário validação Alocação de Alunas nas turmas
![image.png](https://images.zenhubusercontent.com/63758103a71eaa26768642a8/301c0e66-5f2d-4fc6-9dcc-dd5b402cc6d0)
