### ISSUE TITLE
[US07] Logout

### ISSUE THREAD

**Issue by jps12** [fga-eps-mds/2022.2-Amis-Doc#86]
## História do usuário

Eu como Administrador/Assistente desejo fazer logout da plataforma para que minha sessão não fique aberta em um eventual computador coletivo

## Protótipo

[Tela de login](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2FUWVRKI0dvYnnF6lYI76Vzy%2FAMIS-team-library%3Fnode-id%3D450%253A201%26t%3DX7N6brBnQgyFjL7C-1)
[Botão sair](https://user-images.githubusercontent.com/90219532/216213875-d4594205-0889-4b69-9a70-dae4984d41b1.png)

## Critérios de aceitação

Ao clicar no botão sair, a aplicação deve verificar:
- [x] Se o usuário é deslogado com sucesso

**Comment by CaioSulz** [comment]
Formulário de validação Login e Logout

![image](https://user-images.githubusercontent.com/98036264/216772755-65038989-052f-4952-800b-56d9b798dc42.png)
![image](https://user-images.githubusercontent.com/98036264/216772768-04bf10d8-5d23-43f0-bd51-7b6f34fc16f7.png)
