### ISSUE TITLE
[BUG] Correção dos cálculos de documento de custo

### ISSUE THREAD

**Issue by fxred** [fga-eps-mds/2022.2-Amis-Doc#87]
**Descreva o bug**
Falta de informações relacionadas ao cálculo no documento de custo do projeto.

**Comment by jps12** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Amis-6360797e8fcdf43062d4d7b8/issues/fga-eps-mds/2022.2-Amis-Doc/87?planning-poker) with Zenhub @andrelucasf @CaioSulz @FabricioDeQueiroz @fxred @gabrielapivetta @ItaloBrunoM @KalebeLopes @paulohborba @thiagolsg @Jvsoutomaior
